'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class survey

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfMasterID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMasterID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblfirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfirst As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLast As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbHomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHomePhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWork As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbWorkPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCat As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDog As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCat As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbQ1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbQ1A As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq1b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''q1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q1c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq2a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq2b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq2c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq3a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq3b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq3c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq4a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq4a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq4b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq4c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq5a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq5a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq5b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq5c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq6a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq6a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq6b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq6c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq6d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq6d As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq7a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq7a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq7b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq7b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq7c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq7c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq8a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq8a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq8b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq8b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq8c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq8c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq9a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq9a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq9b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq9b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq9c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq9c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq10a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq10a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq10b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq10b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq10c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq10c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq10d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq10d As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq11a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq11a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq11b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq11b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq11c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq11c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq12a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq12a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq12b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq12b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbDateCats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateCats As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbq12c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq12c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq13a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq13a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq13b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq13b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq13c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq13c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq14a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq14a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq14b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq14b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq14c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq14c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq15a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq15a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq15b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq15b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq15c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq15c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbQuestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDog As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''q1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q1a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''q2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q2b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbq1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbq1c As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''q2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q2a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''q3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q3a As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbbreeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbbreeds As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''q3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q3b As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb14 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb15 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb16 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbHourDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHourDay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb17 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb18 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb19 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb20 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb21 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb22 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb23 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb24 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb25 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb26 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb27 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb28 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb29 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb30 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb31 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb32 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb33 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb34 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb35 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb36 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb37 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb38 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb39 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb40 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb41 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb42 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb43 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb44 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb45 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb46 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb47 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cb48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb48 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbQuestionDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbQuestionDog As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDog As Global.System.Web.UI.WebControls.Button
End Class
